stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - docker build -t qiushaocloud/redis-web-admin:latest .
  tags:
    - qiushaocloud-runner

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login --username $DOCKER_HUB_USER_NAME --password $DOCKER_HUB_USER_PASSWORD
    - docker push qiushaocloud/redis-web-admin:latest
  tags:
    - qiushaocloud-runner

build-tags:
  stage: build
  only:
    - tags
  script:
    - docker build -t qiushaocloud/redis-web-admin:latest .
    - docker tag qiushaocloud/redis-web-admin:latest qiushaocloud/redis-web-admin:$CI_COMMIT_REF_NAME
  tags:
    - qiushaocloud-runner

deploy-tags:
  stage: deploy
  only:
    - tags
  script:
    - docker login --username $DOCKER_HUB_USER_NAME --password $DOCKER_HUB_USER_PASSWORD
    - docker push qiushaocloud/redis-web-admin:latest
    - docker push qiushaocloud/redis-web-admin:$CI_COMMIT_REF_NAME
  tags:
    - qiushaocloud-runner
