version:  '3'
services:
  qiushao-redis-web-admin:
      image: qiushaocloud/redis-web-admin
      container_name: qiushao-redis-web-admin
      hostname: qiushao-redis-web-admin
      ports:
        - $EXTERNAL_SVC_PORT:9898
        - $EXTERNAL_MYSQL_PORT:3306
        - $EXTERNAL_TEST_REDIS_PORT:6379
      volumes:
        - $RWA_DATA_DIR:/data
        - $MYSQL_DIR/var_lib_mysql:/var/lib/mysql
        - $MYSQL_DIR/var_run_mysqld:/var/run/mysqld
        - $TEST_REDIS_DIR/var_lib_redis:/var/lib/redis
      env_file: .env